// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADHcTmcC9MHReFBCMlC7rcYNbFWrj72fw',
    appId: '1:928073302109:web:41fd671e6d1896f77e4db4',
    messagingSenderId: '928073302109',
    projectId: 'bdcruddino',
    authDomain: 'bdcruddino.firebaseapp.com',
    storageBucket: 'bdcruddino.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUU9GAQlPJle2pwzocsFAX7vqShkOaMYo',
    appId: '1:928073302109:android:dc015fcb21af815e7e4db4',
    messagingSenderId: '928073302109',
    projectId: 'bdcruddino',
    storageBucket: 'bdcruddino.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDihhZzVBm77Zj4AGeoI_8PDU89W0fHNqI',
    appId: '1:928073302109:ios:38b8a4b9c866dff97e4db4',
    messagingSenderId: '928073302109',
    projectId: 'bdcruddino',
    storageBucket: 'bdcruddino.firebasestorage.app',
    iosBundleId: 'com.example.spideysaurus',
  );
}
